### ISSUE TITLE
RubyGems Submission Absent

### ISSUE THREAD

**Issue by recurrence** [invisiblelines/security_identifiers#1]
Hi Guys,

This gem doesn't seem to have been submitted to ruby gems.  Was that intentional?

Thanks,
Tyler

**Comment by kieranj** [comment]
Hi,

No it wasn't intentional not to push this to Rubygems. After setting up Travis etc, I guess actually releasing the gem was just missed.

I've updated a few dependencies and submitted version 0.1.0 to Rubygems.

Hope you find this useful.
